import { Geist, Geist_Mono } from "next/font/google";
import { playfairBlack } from "@/app/font";

import '@fontsource/plus-jakarta-sans'; // Defaults to weight 400
import '@fontsource/plus-jakarta-sans/500.css'; // Import specific weights if needed
import '@fontsource/plus-jakarta-sans/700.css';
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairBlack.variable} antialiased p-0 m-0`}
      >
        {children}
      </body>
    </html>
  );
}
